"""
Candidate Finder API — FastAPI application entry point.

This is where everything comes together. The API has three endpoints:
  GET  /       — Health check (confirms the server is running)
  POST /search — Main search functionality
  GET  /docs   — Swagger UI (auto-generated by FastAPI)

The search pipeline (in _search_pipeline) has 6 steps:
  1. Parse the requirement using the LLM
  2. Pre-filter candidates using rules
  3. Score shortlisted candidates using the LLM
  4. Apply score threshold
  5. Auto-broaden (bonus feature) if not enough good candidates
  6. Return top 20 with scores and reasons

Usage:
    uvicorn main:app --reload
    # Then POST to http://localhost:8000/search with {"requirement": "..."}
"""

import logging
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from app.config import settings
from app.data_loader import load_candidates
from app.llm_client import LLMClient
from app.matcher import prefilter_candidates
from app.models import (
    Candidate,
    HealthResponse,
    ParsedRequirement,
    ScoredCandidate,
    SearchRequest,
    SearchResponse,
)
from app.requirement_parser import parse_requirement
from app.scorer import score_candidates

# ═══════════════════════════════════════════════════════════════════════════
# Logging Setup
# ═══════════════════════════════════════════════════════════════════════════
# I include timestamps and log levels so it's easy to debug issues.
# The format is: "2026-05-31 15:26:10,310 | module_name | INFO | message"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("candidate_finder")

# ═══════════════════════════════════════════════════════════════════════════
# FastAPI App Initialization
# ═══════════════════════════════════════════════════════════════════════════

app = FastAPI(
    title="Candidate Finder API",
    description=(
        "Search and score candidates using plain-language hiring requirements "
        "with LLM-powered matching."
    ),
    version="1.0.0",
)

# Enable CORS so the API can be called from web browsers during development
# In production, I'd restrict this to specific origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ═══════════════════════════════════════════════════════════════════════════
# Global State
# ═══════════════════════════════════════════════════════════════════════════
# I use module-level variables instead of a database for simplicity.
# The candidates are loaded once at startup and kept in memory.
# The LLM client is also initialized once and reused.

candidates: list[Candidate] = []
llm_client: Optional[LLMClient] = None


# ═══════════════════════════════════════════════════════════════════════════
# Startup Event
# ═══════════════════════════════════════════════════════════════════════════


@app.on_event("startup")
async def startup():
    """
    Runs when the FastAPI server starts.
    
    Two things happen:
    1. Load all 500 candidates from candidates.json into memory
    2. Initialize the LLM client (connects to LM Studio)
    
    If either fails, the app still starts but returns appropriate errors
    when users try to search. This is better than crashing on startup.
    """
    global candidates, llm_client

    logger.info("Starting Candidate Finder API...")

    # ── Load Candidates ────────────────────────────────────────────────
    try:
        candidates = load_candidates(settings.CANDIDATES_PATH)
        logger.info(
            "Loaded %d candidates from %s",
            len(candidates),
            settings.CANDIDATES_PATH,
        )
    except FileNotFoundError as e:
        logger.error("Failed to load candidates: %s", e)
        candidates = []
    except Exception as e:
        logger.error("Unexpected error loading candidates: %s", e)
        candidates = []

    # ── Initialize LLM Client ──────────────────────────────────────────
    try:
        llm_client = LLMClient()
        logger.info("LLM client initialized")
    except Exception as e:
        # If LM Studio isn't running, we log a warning but don't crash.
        # The API will return 503 errors when users try to search.
        logger.warning("Failed to initialize LLM client on startup: %s", e)
        logger.warning("The API will still work but LLM features will fail at runtime")
        llm_client = None


# ═══════════════════════════════════════════════════════════════════════════
# Helper Functions
# ═══════════════════════════════════════════════════════════════════════════


def _get_llm_client() -> LLMClient:
    """
    Get the shared LLM client, creating it if needed.
    
    I use lazy initialization here — if the startup event failed to create
    the client, we try again when the first search request comes in.
    """
    global llm_client
    if llm_client is None:
        llm_client = LLMClient()
    return llm_client


def _search_pipeline(
    requirement_text: str,
    enable_broaden: bool = False,
) -> tuple[list[ScoredCandidate], bool]:
    """
    The main search pipeline — 6 steps from text to results.

    1. Parse the plain-text requirement into structured fields (using LLM)
    2. Pre-filter the 500 candidates using rule-based matching
    3. Score the shortlisted candidates (using LLM, batched)
    4. Apply score threshold (only keep scores >= 50)
    5. Auto-broaden if < 20 good candidates and feature is enabled
    6. Return top 20 with ranks

    Args:
        requirement_text: The recruiter's plain-language requirement.
        enable_broaden: Whether to auto-broaden if too few results.

    Returns:
        Tuple of (top scored candidates, whether broaden was used).
    """
    client = _get_llm_client()

    # ── Step 1: Parse ──────────────────────────────────────────────────
    logger.info("Step 1: Parsing requirement...")
    parsed_req = parse_requirement(requirement_text, client)

    # ── Step 2: Pre-filter ─────────────────────────────────────────────
    logger.info("Step 2: Pre-filtering candidates...")
    shortlist = prefilter_candidates(candidates, parsed_req)
    # shortlist is now ~50-150 candidates (instead of 500)

    # ── Step 3: Score ──────────────────────────────────────────────────
    logger.info("Step 3: Scoring %d candidates with LLM...", len(shortlist))
    scored = score_candidates(shortlist, parsed_req, client)

    # ── Step 4: Apply threshold ────────────────────────────────────────
    # Only keep candidates with score >= 50 (considered "good matches")
    good_candidates = [s for s in scored if s.score >= settings.SCORE_THRESHOLD]

    # ── Step 5: Auto-broaden (bonus feature) ───────────────────────────
    broaden_used = False
    if enable_broaden and len(good_candidates) < settings.TOP_K:
        logger.info(
            "Only %d good candidates found (need %d). Attempting broaden...",
            len(good_candidates),
            settings.TOP_K,
        )
        broadened_results = _attempt_broaden(parsed_req, client, scored)
        if broadened_results:
            # Merge new candidates with existing ones (avoid duplicates)
            existing_names = {s.name for s in good_candidates}
            new_candidates = [
                s for s in broadened_results if s.name not in existing_names
            ]
            merged = good_candidates + new_candidates
            merged.sort(key=lambda x: x.score, reverse=True)
            good_candidates = merged
            broaden_used = True
            logger.info(
                "Broaden added %d more candidates. Total: %d",
                len(new_candidates),
                len(good_candidates),
            )

    # ── Step 6: Return top K ───────────────────────────────────────────
    top_k = good_candidates[: settings.TOP_K]
    for rank, scored_candidate in enumerate(top_k, start=1):
        scored_candidate.rank = rank

    return top_k, broaden_used


def _attempt_broaden(
    original_req: ParsedRequirement,
    client: LLMClient,
    already_scored: list[ScoredCandidate],
) -> list[ScoredCandidate]:
    """
    Bonus feature: relax constraints and search again.

    If the initial search finds fewer than 20 good candidates, this method:
    1. Drops the industry filter first (25% of data is missing industry anyway)
    2. If still no candidates, drops location too
    3. Scores the newly included candidates
    4. Returns any that score >= 50

    I cap this at ONE broaden attempt to prevent infinite loops.
    Without this cap, if the LLM gives weird scores, it could keep
    broadening indefinitely.
    """
    # First try: drop industry, keep location
    relaxed_req = ParsedRequirement(
        title_keywords=original_req.title_keywords,
        min_experience=original_req.min_experience,
        industries=[],  # Industry is the weakest signal — drop it first
        locations=original_req.locations,
        required_skills=original_req.required_skills,
    )

    # Get candidates that weren't in the first pass
    already_scored_names = {s.name for s in already_scored}
    fresh_candidates = [c for c in candidates if c.name not in already_scored_names]

    # Try with relaxed criteria (no industry filter)
    new_shortlist = prefilter_candidates(
        fresh_candidates, relaxed_req, max_candidates=50
    )

    if not new_shortlist:
        # Second try: drop location too
        relaxed_req.locations = []
        new_shortlist = prefilter_candidates(
            fresh_candidates, relaxed_req, max_candidates=50
        )

    if not new_shortlist:
        return []

    # Score the new candidates with the relaxed requirement
    new_scores = score_candidates(new_shortlist, relaxed_req, client)

    # Only return candidates that meet the score threshold
    return [s for s in new_scores if s.score >= settings.SCORE_THRESHOLD]


# ═══════════════════════════════════════════════════════════════════════════
# API Endpoints
# ═══════════════════════════════════════════════════════════════════════════


@app.get("/", response_model=HealthResponse)
async def health_check():
    """
    Simple health check — confirms the API is running and data is loaded.
    
    Returns:
        {"status": "ok", "candidates_loaded": 500}
    """
    return HealthResponse(
        status="ok",
        candidates_loaded=len(candidates),
    )


@app.post("/search", response_model=SearchResponse)
async def search_candidates(request: SearchRequest):
    """
    The main search endpoint — find candidates matching a hiring requirement.
    
    This is the endpoint recruiters will actually use. They send a plain-language
    requirement, and we return the top 20 candidates with scores and reasons.
    
    Example request body:
        {"requirement": "Customer Success Manager, 3+ years, fintech background, Bangalore"}
    
    Example response:
        {
            "query": "Customer Success Manager, 3+ years, fintech background, Bangalore",
            "total_results": 20,
            "broaden_used": false,
            "results": [
                {"rank": 1, "name": "Priya Sharma", "title": "Customer Success Manager",
                 "score": 92, "reason": "CSM title matches, 5yr exp, fintech, Bangalore"}
            ]
        }
    
    I handle errors at three levels:
    1. No candidates loaded → 503 (data issue)
    2. LLM unavailable → 503 (infrastructure issue)
    3. Unexpected errors → 500 (bug)
    """
    # ── Pre-flight checks ──────────────────────────────────────────────
    if not candidates:
        raise HTTPException(
            status_code=503,
            detail="No candidates loaded. Check that candidates.json exists and is valid.",
        )

    requirement_text = request.requirement.strip()
    if not requirement_text:
        raise HTTPException(
            status_code=400,
            detail="Requirement text cannot be empty.",
        )

    # ── Run the pipeline ───────────────────────────────────────────────
    try:
        results, broaden_used = _search_pipeline(
            requirement_text,
            enable_broaden=request.broaden,
        )

        return SearchResponse(
            query=requirement_text,
            total_results=len(results),
            broaden_used=broaden_used,
            results=results,
        )

    except ConnectionError as e:
        # This happens when LM Studio isn't running
        raise HTTPException(
            status_code=503,
            detail=f"LLM service unavailable: {e}",
        )
    except RuntimeError as e:
        # Something went wrong during LLM parsing or scoring
        raise HTTPException(
            status_code=500,
            detail=f"Search failed: {e}",
        )
    except Exception as e:
        # Catch-all for unexpected errors (so the API returns JSON, not a crash)
        logger.exception("Unexpected error during search")
        raise HTTPException(
            status_code=500,
            detail=f"Unexpected error: {e}",
        )
